services:
  video-hangouts-peerjs:
    image: peerjs/peerjs-server:latest
    container_name: video-hangouts-peerjs
    ports:
      - "${VH_PEER_SERVER_PORT}:9000"
    command:
      - --path
      - /peerjs
      - --key
      - ${VH_PEER_SERVER_KEY}
    networks:
      - video-hangouts-network

  video-hangouts-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-hangouts-app
    ports:
      - "${VH_APP_SERVER_PORT}:3000"
    environment:
      VH_APP_SERVER_PORT: 3000
      # peer server
      VH_PEER_SERVER_HOST: ${VH_PEER_SERVER_HOST}
      VH_PEER_SERVER_PORT: ${VH_PEER_SERVER_PORT}
      VH_PEER_SERVER_KEY: ${VH_PEER_SERVER_KEY}
      # stun/turn servers (with ICEs)
      VH_STUN_SERVER_DOMAIN: ${VH_STUN_SERVER_DOMAIN}
      VH_STUN_SERVER_KEY: ${VH_STUN_SERVER_KEY}
      VH_ICE_EXPIRATION_MINUTES: ${VH_ICE_EXPIRATION_MINUTES}
    networks:
      - video-hangouts-network

networks:
  video-hangouts-network:
    driver: bridge
