services:
  webrtc-hangout-peerjs:
    image: peerjs/peerjs-server:latest
    container_name: webrtc-hangout-peerjs
    ports:
      - "${WHA_PEER_SERVER_PORT}:9000"
    command:
      - --path
      - /peerjs
      - --key
      - ${WHA_PEER_SERVER_KEY}
    networks:
      - webrtc-hangout-network

  webrtc-hangout-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrtc-hangout-app
    ports:
      - "${WHA_APP_SERVER_PORT}:3000"
    environment:
      WHA_APP_SERVER_PORT: 3000
      # peer server
      WHA_PEER_SERVER_HOST: ${WHA_PEER_SERVER_HOST}
      WHA_PEER_SERVER_PORT: ${WHA_PEER_SERVER_PORT}
      WHA_PEER_SERVER_KEY: ${WHA_PEER_SERVER_KEY}
      # stun/turn servers (with ICEs)
      WHA_STUN_SERVER_DOMAIN: ${WHA_STUN_SERVER_DOMAIN}
      WHA_STUN_SERVER_KEY: ${WHA_STUN_SERVER_KEY}
      WHA_ICE_EXPIRATION_MINUTES: ${WHA_ICE_EXPIRATION_MINUTES}
    networks:
      - webrtc-hangout-network

networks:
  webrtc-hangout-network:
    driver: bridge
