name: Build and deploy client

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/client.yml"
      - "package.json"
      - "client/**"

env:
  SUBPROJECT_ROOT: "client"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: cd ${{ env.SUBPROJECT_ROOT }} && yarn install --frozen-lockfile

      - name: Build
        run: cd ${{ env.SUBPROJECT_ROOT }} && yarn run build

      - name: Upload generated dist files
        uses: actions/upload-artifact@v4
        with:
          name: dist-output
          path: ${{ env.SUBPROJECT_ROOT }}/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SERVER_OUTPUT: "/var/www/webrtc-video-hangouts-client"

    steps:
      - name: Download generated dist files
        uses: actions/download-artifact@v4
        with:
          name: dist-output
          path: dist

      - name: Move files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dist/*"
          target: ${{ env.SERVER_OUTPUT }}
          rm: true
          strip_components: 1
